### ISSUE TITLE
good afternoon Doctor

### ISSUE THREAD

**Issue by Huangzhizhong123** [lucidrains/graph-transformer-pytorch#1]
why is edges's dimension 512.   I think it is Adjacency matrix which is 2 dimensions like [1024,1024]

**Comment by willyfh** [comment]
> why is edges's dimension 512. I think it is Adjacency matrix which is 2 dimensions like [1024,1024]

512 is the edge feature. Consider each connection has edge feature representation. Regarding the adjacency matrix which the value is 1 or 0, from what I understand, the implementation of this repository seems doesn't consider the adjacency matrix. I'm not sure why the adjacency matrix is omitted here. Since it is actually important during the aggregation and also the calculation of the attention score.

**Comment by lucidrains** [comment]
@Huangzhizhong123 @willyfh at the time, i thought the adjacency could be embedded and passed in as the edges

but on further thought, it would be good to support it like you said (accepting a boolean tensor of shape `batch, 1024, 1024`) https://github.com/lucidrains/graph-transformer-pytorch/commit/35864adde12ffd03e68ac101e68368d25ee42bd7

**Comment by lucidrains** [comment]
also, no need to address me as doctor. only people i dislike have to address me that way :laughing:
